name: Docker Build and Push

on:
  push:
    branches:
      - master
  
env:
  username: ${{ secrets.DOCKER_ID }}
  password: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build client Docker test image
        run: |
          docker build -t bujaretemi1998/react-test -f ./client/Dockerfile.dev ./client
      
      - name: Run tests
        run: |
          docker run -e CI=true bujaretemi1998/react-test npm test -- --coverage

      - name: Build Docker images login and push
        run: |
          docker build -t bujaretemi1998/multi-client:multi-client ./client
          docker build -t bujaretemi1998/multi-nginx:multi-nginx ./nginx
          docker build -t bujaretemi1998/multi-server:multi-server ./server
          docker build -t bujaretemi1998/multi-worker:multi-worker ./worker
          echo --password ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_ID }}
          
      - name: Push images to Docker Hub
        run: |
          sudo docker push bujaretemi1998/multi-client:multi-client
          sudo docker push bujaretemi1998/multi-nginx:multi-nginx
          sudo docker push bujaretemi1998/multi-server:multi-server
          sudo docker push bujaretemi1998/multi-worker:multi-worker
