name: Docker Build and Push

on:
  push:
    branches:
      - master
      
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_ID }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build client Docker test image
        run: |
          docker build -t bujaretemi1998/react-test -f ./client/Dockerfile.dev ./client
      
      - name: Run tests
        run: |
          docker run -e CI=true bujaretemi1998/react-test npm test -- --coverage
          
      - name: Build Docker images and Log in to Docker Hub
        run: |
          docker build -t bujaretemi1998/multi-client:latest ./client
          docker build -t bujaretemi1998/multi-nginx:latest ./nginx
          docker build -t bujaretemi1998/multi-server:latest ./server
          docker build -t bujaretemi1998/multi-worker:latest ./worker

      - name: Push images to Docker Hub
        run: |
          sudo docker push bujaretemi1998/multi-client
          sudo docker push bujaretemi1998/multi-nginx
          sudo docker push bujaretemi1998/multi-server
          sudo docker push bujaretemi1998/multi-worker
