name: Docker Build and Push

on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          tag_with_sha: true

      - name: Build client Docker test image
        run: |
          docker build -t bujaretemi1998/react-test -f ./client/Dockerfile.dev ./client
      
      - name: Run tests
        run: |
          docker run -e CI=true bujaretemi1998/react-test npm test -- --coverage

      - name: Build Docker images
        run: |
          docker build -t bujaretemi1998/multi-client ./client
          docker build -t bujaretemi1998/multi-nginx ./nginx
          docker build -t bujaretemi1998/multi-server ./server
          docker build -t bujaretemi1998/multi-worker ./worker 
          
      - name: Push images to Docker Hub
        run: |
          docker push bujaretemi1998/multi-client
          docker push bujaretemi1998/multi-nginx
          docker push bujaretemi1998/multi-server
          docker push bujaretemi1998/multi-worker

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: "multi-docker"
          environment_name: "MultiDocker-env"
          bucket_name: "elasticbeanstalk-us-east-1-161134197230"
          bucket_path: "docker-multi"
          region: "us-east-1" # Change to your desired region
          version_label: Sample Application-1


        
