name: Docker Build and Push

on:
  push:
    branches:
      - master
  
env:
  username: ${{ secrets.DOCKER_ID }}
  password: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build client Docker test image
        run: |
          docker build -t bujaretemi1998/react-test -f ./client/Dockerfile.dev ./client
      
      - name: Run tests
        run: |
          docker run -e CI=true bujaretemi1998/react-test npm test -- --coverage

      - name: Build Docker images login and push
        run: |
          docker build -t bujaretemi1998/multi-client:latest ./client
          docker build -t bujaretemi1998/multi-nginx:latest ./nginx
          docker build -t bujaretemi1998/multi-server:latest ./server
          docker build -t bujaretemi1998/multi-worker:latest ./worker
          echo --password-stdin ${{ secrets.DOCKER_PASSWORD }} | docker login ${{ secrets.DOCKER_ID }}
          
      - name: Push images to Docker Hub
        run: |
          docker push bujaretemi1998/multi-client:latest
          docker push bujaretemi1998/multi-nginx:latest
          docker push bujaretemi1998/multi-server:latest
          docker push bujaretemi1998/multi-worker:latest
