name: Docker Build and Push

on:
  push:
    branches:
      - master

env:
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build client Docker image
        run: |
          docker build -t bujaretemi1998/react-test -f ./client/Dockerfile.dev ./client
      
      - name: Run tests
        run: |
          docker run bujaretemi1998/react-test npm test -- --coverage

      - name: Build and push Docker images
        run: |
          docker build -t bujaretemi1998/multi-client ./client
          docker build -t bujaretemi1998/multi-nginx ./nginx
          docker build -t bujaretemi1998/multi-server ./server
          docker build -t bujaretemi1998/multi-worker ./worker
          
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER
