name: Docker Build and Push

on:
  push:
    branches:
      - master
      
env:
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  TAG_NAME: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build client Docker test image
        run: |
          docker build -t bujaretemi1998/react-test:$TAG_NAME -f ./client/Dockerfile.dev ./client
      
      - name: Run tests
        run: |
          docker run -e CI=true bujaretemi1998/react-test:$TAG_NAME npm test -- --coverage

      - name: Build Docker images, login to Docker Hub and push
        run: |
          docker build -t bujaretemi1998/multi-client:$TAG_NAME ./client
          docker build -t bujaretemi1998/multi-nginx:$TAG_NAME ./nginx
          docker build -t bujaretemi1998/multi-server:$TAG_NAME ./server
          docker build -t bujaretemi1998/multi-worker:$TAG_NAME ./worker
          echo $DOCKER_PASSWORD | docker login $DOCKER_ID
          
      - name: check push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          
      - name: Push images to Docker Hub
        run: |
          docker push bujaretemi1998/multi-client:$TAG_NAME
          docker push bujaretemi1998/multi-nginx:$TAG_NAME
          docker push bujaretemi1998/multi-server:$TAG_NAME
          docker push bujaretemi1998/multi-worker:$TAG_NAME
