name: Docker Build and Push

on:
  push:
    branches:
      - master
      
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker.DOCKER_USERNAME }}
          password: ${{ env.docker.DOCKER_PASSWORD }}

      - name: Build client Docker test image
        run: |
          docker build -t bujaretemi1998/react-test -f ./client/Dockerfile.dev ./client
      
      - name: Run tests
        run: |
          docker run -e CI=true bujaretemi1998/react-test npm test -- --coverage

      - name: Build Docker images
        run: |
          docker build -t bujaretemi1998/multi-client ./client
          docker build -t bujaretemi1998/multi-nginx ./nginx
          docker build -t bujaretemi1998/multi-server ./server
          docker build -t bujaretemi1998/multi-worker ./worker 
          
      - name: Push images to Docker Hub
        run: |
          docker push bujaretemi1998/multi-client
          docker push bujaretemi1998/multi-nginx
          docker push bujaretemi1998/multi-server
          docker push bujaretemi1998/multi-worker
