name: Docker Build and Push

on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          tag_with_sha: true

      - name: Build client Docker test image
        run: |
          docker build -t bujaretemi1998/react-test -f ./client/Dockerfile.dev ./client
      
      - name: Run tests
        run: |
          docker run -e CI=true bujaretemi1998/react-test npm test -- --coverage

      - name: Build Docker images
        run: |
          docker build -t bujaretemi1998/multi-client2 ./client
          
      - name: Push images to Docker Hub
        run: |
          docker push bujaretemi1998/multi-client2

        
