name: Docker Build and Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image for client
      run: |
        docker build -t bujaretemi1998/react-test -f ./client/Dockerfile.dev ./client

    - name: Run tests
      run: docker run -e CI=true bujaretemi1998/react-test npm test -- --coverage

    - name: Build Docker images for multi-client, multi-nginx, multi-server, and multi-worker
      run: |
        docker build -t bujaretemi1998/multi-client ./client
        docker build -t bujaretemi1998/multi-nginx ./nginx
        docker build -t bujaretemi1998/multi-server ./server
        docker build -t bujaretemi1998/multi-worker ./worker
        echo docker login --username="$DOCKER_ID" | --password="$DOCKER_PASSWORD" --password-stdin
        
        
    - name: Log in to Docker CLI and push images to Docker Hub
      run: |
        docker push bujaretemi1998/multi-client
        docker push bujaretemi1998/multi-nginx
        docker push bujaretemi1998/multi-server
        docker push bujaretemi1998/multi-worker
