name: Docker Build and Push

on:
  push:
    branches:
      - master
      
env:
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build client Docker test image
        run: |
          docker build -t bujaretemi1998/react-test -f ./client/Dockerfile.dev ./client
      
      - name: Run tests
        run: |
          sudo docker run -t -e CI=true bujaretemi1998/react-test npm test -- --coverage

      - name: Build Docker images
        run: |
          sudo docker build -t bujaretemi1998/multi-client ./client
          sudo docker build -t bujaretemi1998/multi-nginx ./nginx
          sudo docker build -t bujaretemi1998/multi-server ./server
          sudo docker build -t bujaretemi1998/multi-worker ./worker
          sudo docker run --rm -it -v "$(pwd)":/app ubuntu bash
          echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login --username ${{ secrets.DOCKER_ID }} --password-stdin
          
              
      - name: Push images to Docker Hub
        run: |
          sudo --non-interactive docker push -t bujaretemi1998/multi-client
          sudo --non-interactive docker push -t bujaretemi1998/multi-nginx
          sudo --non-interactive docker push -t bujaretemi1998/multi-server
          sudo --non-interactive docker push -t bujaretemi1998/multi-worker
