name: Docker Build and Push

on:
  push:
    branches:
      - master
  
env:
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Modify Docker daemon configuration
        run: |
          sudo mkdir -p /etc/systemd/system/docker.service.d
          echo '[Service]
          ExecStart=
          ExecStart=/usr/bin/dockerd -D -H fd:// -H tcp://0.0.0.0:2375 --host=unix:///var/run/docker.sock' | sudo tee /etc/systemd/system/docker.service.d/startup_options.conf
          sudo systemctl daemon-reload
          sudo systemctl restart docker

      - name: Build client Docker test image
        run: |
          docker build -t bujaretemi1998/react-test -f ./client/Dockerfile.dev ./client
      
      - name: Run tests
        run: |
          docker run -e CI=true bujaretemi1998/react-test npm test -- --coverage

      - name: Build Docker images
        run: |
          docker build bujaretemi1998/multi-client ./client
          docker build bujaretemi1998/multi-nginx ./nginx
          docker build bujaretemi1998/multi-server ./server
          docker build bujaretemi1998/multi-worker ./worker
          echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login --username ${{ secrets.DOCKER_ID }} --password-stdin
          
              
      - name: Push images to Docker Hub
        run: |
          docker push bujaretemi1998/multi-client
          docker push bujaretemi1998/multi-nginx
          docker push bujaretemi1998/multi-server
          docker push bujaretemi1998/multi-worker
